language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

install:
  - composer install

script:
  - phpunit

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

after_script:
  - vendor/bin/test-reporter
